# Default values
DOWNLOAD_URL=https://www.github.com/mardous/BoomingMusic/releases/latest
DONATION_LINK=https://ko-fi.com/christiaam
GITHUB_API_URL=https://api.github.com/
LYRICALLY_API_URL=https://lyrics.paxsenix.org/apple-music/lyrics

# F-Droid overrides
fdroid.DOWNLOAD_URL=https://f-droid.org/packages/com.mardous.booming/
fdroid.GITHUB_API_URL=

# Play Store overrides
playstore.DOWNLOAD_URL=https://play.google.com/store/apps/details?id=com.mardous.booming
playstore.DONATION_LINK=
playstore.GITHUB_API_URL=
playstore.LYRICALLY_API_URL=