package com.mardous.booming.coil

import android.content.ClipDescription
import android.content.ContentProvider
import android.content.ContentResolver
import android.content.ContentValues
import android.content.Context
import android.content.UriMatcher
import android.content.res.AssetFileDescriptor
import android.database.Cursor
import android.graphics.Bitmap
import android.graphics.Point
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.os.CancellationSignal
import android.os.Handler
import android.os.HandlerThread
import android.os.MemoryFile
import android.os.OperationCanceledException
import android.os.ParcelFileDescriptor
import android.os.ProxyFileDescriptorCallback
import android.os.storage.StorageManager
import android.util.Log
import androidx.core.content.getSystemService
import androidx.core.os.BundleCompat
import coil3.ColorImage
import coil3.SingletonImageLoader
import coil3.decode.DecodeResult
import coil3.decode.Decoder
import coil3.fetch.SourceFetchResult
import coil3.request.CachePolicy
import coil3.request.ImageRequest
import coil3.request.Options
import coil3.request.allowHardware
import coil3.size.Size
import coil3.toBitmap
import com.mardous.booming.BuildConfig
import com.mardous.booming.coil.model.AutoGeneratedImage
import com.mardous.booming.data.local.repository.Repository
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.CoroutineStart
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.InternalCoroutinesApi
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.currentCoroutineContext
import kotlinx.coroutines.ensureActive
import kotlinx.coroutines.job
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import okio.BufferedSource
import org.koin.core.component.KoinComponent
import org.koin.core.component.inject
import java.io.ByteArrayOutputStream
import java.io.FileDescriptor
import kotlin.math.min
import kotlin.time.Duration.Companion.milliseconds

/**
 * Based on Gramophone's implementation.
 *
 * See: https://github.com/FoedusProgramme/Gramophone
 */
class CoverProvider : ContentProvider(), KoinComponent {

    private val repository by inject<Repository>()

    override fun onCreate(): Boolean = true

    private fun getSmallSize(context: Context): Point {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            // refer to mThumbSize in MediaProvider.java
            val metrics = context.applicationContext.resources.displayMetrics
            val thumbSize = min(metrics.widthPixels, metrics.heightPixels) / 2
            return Point(thumbSize, thumbSize)
        }
        return Point(SMALL_SIZE, SMALL_SIZE)
    }

    @OptIn(InternalCoroutinesApi::class)
    private suspend fun openFileCommon(
        uri: Uri,
        size: Point?
    ): AssetFileDescriptor? {
        val context = context ?: return null
        val cfd = CompletableDeferred<AssetFileDescriptor?>()
        val scope = CoroutineScope(Dispatchers.IO + SupervisorJob())

        currentCoroutineContext().job.invokeOnCompletion {
            if (it is CancellationException) scope.cancel(it)
            else if (it != null) scope.cancel("Error in parent block", it)
        }

        scope.launch {
            currentCoroutineContext().job.invokeOnCompletion {
                if (!cfd.isCompleted) {
                    cfd.completeExceptionally(
                        it ?: IllegalStateException("Completed job without setting file descriptor")
                    )
                }
            }

            val data = getDataForUri(uri)
            if (data == null) {
                cfd.complete(null)
                return@launch
            }

            SingletonImageLoader.get(context).execute(
                ImageRequest.Builder(context)
                    .data(data)
                    .let { request ->
                        if (size != null) {
                            request.size(size.x, size.y)
                        } else if (uri.getBooleanQueryParameter("hd", false)) {
                            request
                        } else {
                            // Default small size for browser/queue
                            request.size { getSmallSize(context).run { Size(x, y) } }
                        }
                    }
                    .memoryCachePolicy(CachePolicy.WRITE_ONLY)
                    .allowHardware(false)
                    .decoderFactory { result: SourceFetchResult, options: Options, _ ->
                        val src: BufferedSource = result.source.source()
                        src.peek().let { peekSrc: BufferedSource ->
                            try {
                                if (peekSrc.readByte() != 0xff.toByte() ||
                                    peekSrc.readByte() != 0xd8.toByte() ||
                                    peekSrc.readByte() != 0xff.toByte() ||
                                    run {
                                        val peek = peekSrc.readByte()
                                        peek != 0xdb.toByte() && peek !in 0xe0.toByte()..0xef.toByte()
                                    }
                                ) {
                                    // Not JPEG. We'll have to re-encode to JPEG
                                    return@decoderFactory null
                                }
                            } catch (_: Exception) {
                                return@decoderFactory null
                            }
                        }
                        Decoder {
                            if (!cfd.isCompleted) {
                                writeDataCommon(cfd, scope, options.context) {
                                    src.readByteArray()
                                }
                            }
                            // shareable is false to avoid writing dummy to memory cache
                            DecodeResult(
                                image = ColorImage(0, shareable = false),
                                isSampled = false
                            )
                        }
                    }
                    .target(
                        onSuccess = { image ->
                            if (!cfd.isCompleted) {
                                launch(start = CoroutineStart.ATOMIC) {
                                    writeDataCommon(cfd, scope, context) {
                                        val os = ByteArrayOutputStream()
                                        image.toBitmap().compress(Bitmap.CompressFormat.JPEG, 95, os)
                                        os.toByteArray()
                                    }
                                }
                            }
                        }
                    )
                    .listener(
                        onError = { _, result ->
                            if (cfd.isCompleted) {
                                Log.e(TAG, "Listener errored after successful decode", result.throwable)
                                return@listener
                            }
                            cfd.complete(null)
                        }
                    )
                    .build()
            )
        }
        return cfd.await()
    }

    private suspend fun getDataForUri(uri: Uri): Any? {
        val matchCode = uriMatcher.match(uri)
        if (matchCode == -1) return null

        val id = uri.lastPathSegment ?: return null
        val idAsLong = id.toLongOrNull()

        return when (matchCode) {
            SONG_COVER_CODE -> idAsLong?.let { repository.songById(it) }
            ALBUM_COVER_CODE -> idAsLong?.let { repository.albumById(it) }
            ARTIST_COVER_CODE -> idAsLong?.let { repository.artistById(it) }
            ALBUM_ARTIST_COVER_CODE -> repository.albumArtistByName(id)
            PLAYLIST_COVER_CODE -> idAsLong?.let { repository.playlistWithSongs(it) }
            GENRE_COVER_CODE -> {
                idAsLong?.let {
                    AutoGeneratedImage(
                        type = AutoGeneratedImage.TYPE_GENRE,
                        id = it,
                        songCount = repository.songsByGenre(it).size
                    )
                }
            }
            else -> null
        }
    }

    @OptIn(InternalCoroutinesApi::class)
    private suspend fun writeDataCommon(
        cfd: CompletableDeferred<AssetFileDescriptor?>,
        scope: CoroutineScope,
        context: Context,
        callback: () -> ByteArray
    ) {
        currentCoroutineContext().job.ensureActive()
        val bytes = callback()
        currentCoroutineContext().job.ensureActive()

        // 1. Try Ashmem
        try {
            val memoryFile = MemoryFile("${context.packageName}.albumart", bytes.size)
            val pfd = try {
                val fd = memoryFile.javaClass.getMethod("getFileDescriptor")
                    .invoke(memoryFile) as FileDescriptor
                memoryFile.writeBytes(bytes, 0, 0, bytes.size)
                ParcelFileDescriptor.dup(fd)
            } finally {
                memoryFile.close()
            }
            cfd.complete(AssetFileDescriptor(pfd, 0, AssetFileDescriptor.UNKNOWN_LENGTH))
            return
        } catch (e: Exception) {
            Log.e(TAG, "failed to create ashmem file", e)
        }

        // 2. Try FUSE
        val ht = HandlerThread("pfd_${System.currentTimeMillis()}")
        ht.start()
        var bytesRef: ByteArray? = bytes
        val pfd = try {
            context.getSystemService<StorageManager>()?.openProxyFileDescriptor(
                ParcelFileDescriptor.MODE_READ_ONLY,
                object : ProxyFileDescriptorCallback() {
                    override fun onGetSize(): Long = bytesRef?.size?.toLong() ?: 0L
                    override fun onRead(offset: Long, size: Int, data: ByteArray): Int {
                        val off = offset.toInt()
                        var sz = size
                        val b = bytesRef ?: return 0
                        if (off + sz > b.size) {
                            sz = b.size - off
                        }
                        if (sz <= 0) return 0
                        System.arraycopy(b, off, data, 0, sz)
                        return sz
                    }
                    override fun onRelease() {
                        ht.quitSafely()
                        bytesRef = null
                    }
                }, Handler(ht.looper)
            )
        } catch (e: Exception) {
            Log.e(TAG, "failed to create fuse mount", e)
            null
        }

        if (pfd != null) {
            cfd.complete(AssetFileDescriptor(pfd, 0, AssetFileDescriptor.UNKNOWN_LENGTH))
            return
        } else {
            ht.quitSafely()
        }

        // 3. Fallback to Pipes
        val pipe = ParcelFileDescriptor.createPipe()
        cfd.complete(AssetFileDescriptor(pipe[0], 0, AssetFileDescriptor.UNKNOWN_LENGTH))

        val disposable = scope.coroutineContext[Job]!!.invokeOnCompletion(onCancelling = true) {
            if (it is CancellationException) {
                try { pipe[1].close() } catch (_: Exception) {}
            }
        }

        try {
            withTimeout((30 * 1000).milliseconds) {
                launch(Dispatchers.IO, start = CoroutineStart.ATOMIC) {
                    ParcelFileDescriptor.AutoCloseOutputStream(pipe[1]).use { os ->
                        ensureActive()
                        try {
                            os.write(bytes)
                        } catch (e: Exception) {
                            try { ensureActive() } catch (e2: CancellationException) {
                                e2.addSuppressed(e)
                                throw e2
                            }
                            throw e
                        }
                    }
                    disposable.dispose()
                }.join()
            }
        } catch (_: Exception) {
            scope.cancel()
        }
    }

    private fun openFileCommon(
        uri: Uri,
        size: Point?,
        signal: CancellationSignal?
    ): AssetFileDescriptor? {
        if (uri.pathSegments.size < 2) throw IllegalArgumentException("Invalid uri: $uri")
        return runBlocking {
            signal?.throwIfCanceled()
            val job = currentCoroutineContext().job
            signal?.setOnCancelListener { job.cancel() }
            openFileCommon(uri, size)
        }
    }

    override fun openFile(
        uri: Uri,
        mode: String,
        signal: CancellationSignal?
    ): ParcelFileDescriptor? {
        try {
            if (mode != "r") throw IllegalArgumentException("Read-only provider")
            val afd = openFileCommon(uri, null, signal)
            if (afd != null && (afd.declaredLength != AssetFileDescriptor.UNKNOWN_LENGTH || afd.startOffset != 0L)) {
                // We don't support partial offsets for openFile return as PFD
                return null
            }
            return afd?.parcelFileDescriptor
        } catch (_: CancellationException) {
            throw OperationCanceledException()
        } catch (e: Exception) {
            Log.e(TAG, "Failed to load $uri", e)
            throw e
        }
    }

    override fun openAssetFile(
        uri: Uri,
        mode: String,
        signal: CancellationSignal?
    ): AssetFileDescriptor? {
        try {
            if (mode != "r") throw IllegalArgumentException("Read-only provider")
            return openFileCommon(uri, null, signal)
        } catch (_: CancellationException) {
            throw OperationCanceledException()
        } catch (e: Exception) {
            Log.e(TAG, "Failed to load $uri", e)
            throw e
        }
    }

    override fun openTypedAssetFile(
        uri: Uri,
        mimeTypeFilter: String,
        opts: Bundle?,
        signal: CancellationSignal?
    ): AssetFileDescriptor? {
        try {
            if (ClipDescription.compareMimeTypes("image/jpeg", mimeTypeFilter)) {
                val size = opts?.let {
                    BundleCompat.getParcelable(it, ContentResolver.EXTRA_SIZE, Point::class.java)
                }
                return openFileCommon(uri, size, signal)
            }
            return null
        } catch (_: CancellationException) {
            throw OperationCanceledException()
        } catch (e: Exception) {
            Log.e(TAG, "Failed to load $uri", e)
            throw e
        }
    }

    override fun getType(uri: Uri): String {
        return "image/jpeg"
    }

    override fun query(
        uri: Uri,
        projection: Array<out String>?,
        selection: String?,
        selectionArgs: Array<out String>?,
        sortOrder: String?
    ): Cursor = throw UnsupportedOperationException()

    override fun insert(uri: Uri, values: ContentValues?): Uri? = null
    override fun delete(uri: Uri, selection: String?, selectionArgs: Array<out String>?): Int = 0
    override fun update(uri: Uri, values: ContentValues?, selection: String?, selectionArgs: Array<out String>?): Int = 0

    companion object {
        private const val TAG = "CoverProvider"
        private const val AUTHORITY = "${BuildConfig.APPLICATION_ID}.cover"
        private const val SMALL_SIZE = 512

        const val SONG_COVER_PATH = "song"
        private const val SONG_COVER_CODE = 1
        const val ALBUM_COVER_PATH = "album"
        private const val ALBUM_COVER_CODE = 2
        const val ARTIST_COVER_PATH = "artist"
        private const val ARTIST_COVER_CODE = 3
        const val ALBUM_ARTIST_COVER_PATH = "album_artist"
        private const val ALBUM_ARTIST_COVER_CODE = 4
        const val PLAYLIST_COVER_PATH = "playlist"
        private const val PLAYLIST_COVER_CODE = 5
        const val GENRE_COVER_PATH = "genre"
        private const val GENRE_COVER_CODE = 6

        private val uriMatcher = UriMatcher(UriMatcher.NO_MATCH).apply {
            addURI(AUTHORITY, "$SONG_COVER_PATH/*", SONG_COVER_CODE)
            addURI(AUTHORITY, "$ALBUM_COVER_PATH/*", ALBUM_COVER_CODE)
            addURI(AUTHORITY, "$ARTIST_COVER_PATH/*", ARTIST_COVER_CODE)
            addURI(AUTHORITY, "$ALBUM_ARTIST_COVER_PATH/*", ALBUM_ARTIST_COVER_CODE)
            addURI(AUTHORITY, "$PLAYLIST_COVER_PATH/*", PLAYLIST_COVER_CODE)
            addURI(AUTHORITY, "$GENRE_COVER_PATH/*", GENRE_COVER_CODE)
        }

        fun getImageUri(path: String, id: Long) = getImageUri(path, id.toString())
        fun getImageUri(path: String, id: String): Uri? {
            return Uri.Builder()
                .scheme(ContentResolver.SCHEME_CONTENT)
                .authority(AUTHORITY)
                .appendPath(path)
                .appendPath(id)
                .build()
        }
    }
}
