package com.mardous.booming.coil

import android.content.ContentProvider
import android.content.ContentResolver
import android.content.ContentValues
import android.content.Context
import android.content.UriMatcher
import android.content.res.Configuration
import android.database.Cursor
import android.graphics.Bitmap
import android.graphics.Color
import android.net.Uri
import android.os.ParcelFileDescriptor
import android.util.Log
import androidx.appcompat.app.AppCompatDelegate
import androidx.appcompat.view.ContextThemeWrapper
import androidx.core.graphics.drawable.toBitmap
import coil3.SingletonImageLoader
import coil3.request.CachePolicy
import coil3.request.ImageRequest
import coil3.size.Precision
import coil3.toBitmap
import com.google.android.material.color.DynamicColors
import com.google.android.material.color.DynamicColorsOptions
import com.mardous.booming.BuildConfig
import com.mardous.booming.coil.model.AutoGeneratedImage
import com.mardous.booming.data.local.repository.Repository
import com.mardous.booming.extensions.createAppTheme
import com.mardous.booming.extensions.resolveColor
import com.mardous.booming.ui.component.views.PlaceholderDrawable
import com.mardous.booming.ui.component.views.getPlaceholderDrawable
import com.mardous.booming.util.Preferences
import kotlinx.coroutines.runBlocking
import kotlinx.io.IOException
import org.koin.core.component.KoinComponent
import org.koin.core.component.inject
import java.io.File

class CoverProvider : ContentProvider(), KoinComponent {

    private val repository by inject<Repository>()

    override fun onCreate(): Boolean = true

    override fun openFile(uri: Uri, mode: String): ParcelFileDescriptor? {
        val matchCode = uriMatcher.match(uri)
        if (mode != "r" || matchCode == -1) {
            return null
        }

        val id = uri.lastPathSegment ?: return null
        val idAsLong = id.toLongOrNull()
        if (idAsLong == null && matchCode != ALBUM_ARTIST_COVER_CODE) return null

        val context = this.context ?: return null
        val cacheDir = context.cacheDir.resolve(CACHE_DIR_NAME)
        if (!cacheDir.isDirectory && !cacheDir.mkdirs()) return null

        val masked = matchCode == COOKIE_COVER_CODE
        val dataCode = if (masked) SONG_COVER_CODE else matchCode
        val format = if (masked) Bitmap.CompressFormat.PNG else Bitmap.CompressFormat.JPEG

        val cacheFile = File(cacheDir, "${matchCode}_${id}.${format.extension}")
        val cacheFileExpired = (System.currentTimeMillis() - cacheFile.lastModified()) > CACHE_FILE_EXPIRES
        if (cacheFile.isFile && cacheFile.length() > 0 && !cacheFileExpired) {
            try {
                return ParcelFileDescriptor.open(cacheFile, ParcelFileDescriptor.MODE_READ_ONLY)
            } catch (e: IOException) {
                Log.e(TAG, "ParcelFileDescriptor.open($cacheFile): failed", e)
            }
        }

        // A cover request must never throw back at the caller
        val result = runCatching {
            runBlocking {
                val data = when (dataCode) {
                    SONG_COVER_CODE -> repository.songById(idAsLong!!)
                    ALBUM_COVER_CODE -> repository.albumById(idAsLong!!)
                    ARTIST_COVER_CODE -> repository.artistById(idAsLong!!)
                    ALBUM_ARTIST_COVER_CODE -> repository.albumArtistByName(id)
                    PLAYLIST_COVER_CODE -> repository.playlistWithSongs(idAsLong!!)
                    GENRE_COVER_CODE -> {
                        AutoGeneratedImage(
                            type = AutoGeneratedImage.TYPE_GENRE,
                            id = idAsLong!!,
                            songCount = repository.songsByGenre(idAsLong).size
                        )
                    }
                    else -> null
                }
                if (data != null) {
                    SingletonImageLoader.get(context).execute(
                        ImageRequest.Builder(context)
                            .data(data)
                            .memoryCachePolicy(CachePolicy.DISABLED)
                            .precision(Precision.EXACT)
                            .size(MAX_BITMAP_DIMENSION)
                            .build()
                    )
                } else null
            }
        }.onFailure {
            Log.e(TAG, "Couldn't resolve cover for $uri", it)
        }.getOrNull()

        if (result != null) {
            val bitmap = result.image?.toBitmap()?.let { if (masked) CookieMask.apply(context, it) else it }
            if (bitmap != null && (cacheFile.exists() || cacheFile.createNewFile())) {
                val compressed = try {
                    cacheFile.outputStream().use { bitmap.compress(format, 100, it) }
                } catch (e: IOException) {
                    Log.d(TAG, "Couldn't compress bitmap data to cache file $cacheFile", e)
                    cacheFile.delete()
                    false
                }
                if (compressed) {
                    return ParcelFileDescriptor.open(cacheFile, ParcelFileDescriptor.MODE_READ_ONLY)
                }
            }
        }

        return runCatching { getOrCreateFallback(context, cacheDir, masked) }
            .onFailure { Log.e(TAG, "Couldn't build the fallback cover", it) }
            .getOrNull()
    }

    /** Serialized so concurrent misses render once instead of overwriting each other's output */
    @Synchronized
    private fun getOrCreateFallback(
        context: Context,
        cacheDir: File,
        masked: Boolean
    ): ParcelFileDescriptor? {
        val themed = context.themedForFallback()

        val key = themed.placeholderKey()
        val format = if (masked) Bitmap.CompressFormat.PNG else Bitmap.CompressFormat.JPEG
        val shape = if (masked) "_cookie" else ""
        val cacheFile = File(cacheDir, "${FALLBACK_PREFIX}_$key$shape.${format.extension}")
        if (cacheFile.isFile && cacheFile.length() > 0) {
            return ParcelFileDescriptor.open(cacheFile, ParcelFileDescriptor.MODE_READ_ONLY)
        }

        cacheDir.listFiles { file -> file.name.startsWith(FALLBACK_PREFIX) && !file.name.contains(key) }
            ?.forEach { it.delete() }

        val placeholder = themed.getPlaceholderDrawable(DEFAULT_SONG_IMAGE)
            .toBitmap(FALLBACK_DIMENSION, FALLBACK_DIMENSION)
        val bitmap = if (masked) CookieMask.apply(context, placeholder) else placeholder
        val success = try {
            cacheFile.outputStream().use { bitmap.compress(format, 100, it) }
        } catch (_: Exception) {
            cacheFile.delete()
            false
        } finally {
            if (masked) bitmap.recycle()
            placeholder.recycle()
        }

        return if (success) {
            ParcelFileDescriptor.open(cacheFile, ParcelFileDescriptor.MODE_READ_ONLY)
        } else null
    }


    override fun getType(uri: Uri): String {
        check(uriMatcher.match(uri) != UriMatcher.NO_MATCH) { "Unknown URI: $uri" }
        return "image/*"
    }

    override fun query(
        uri: Uri,
        projection: Array<out String>?,
        selection: String?,
        selectionArgs: Array<out String>?,
        sortOrder: String?
    ): Cursor = throw UnsupportedOperationException()

    override fun insert(uri: Uri, values: ContentValues?): Uri? = null

    override fun delete(uri: Uri, selection: String?, selectionArgs: Array<out String>?): Int = 0

    override fun update(
        uri: Uri,
        values: ContentValues?,
        selection: String?,
        selectionArgs: Array<out String>?
    ): Int = 0

    companion object {
        private const val TAG = "CoilImageProvider"

        private const val AUTHORITY = "${BuildConfig.APPLICATION_ID}.cover"
        private const val CACHE_DIR_NAME = "covers"
        private const val CACHE_FILE_EXPIRES = (60 * 60 * 1000) * 24 * 7 // 7 days
        private const val MAX_BITMAP_DIMENSION = 1024
        private const val FALLBACK_PREFIX = "fallback"
        private const val FALLBACK_DIMENSION = 512

        const val SONG_COVER_PATH = "song"
        private const val SONG_COVER_CODE = 1
        const val ALBUM_COVER_PATH = "album"
        private const val ALBUM_COVER_CODE = 2
        const val ARTIST_COVER_PATH = "artist"
        private const val ARTIST_COVER_CODE = 3
        const val ALBUM_ARTIST_COVER_PATH = "album_artist"
        private const val ALBUM_ARTIST_COVER_CODE = 4
        const val PLAYLIST_COVER_PATH = "playlist"
        private const val PLAYLIST_COVER_CODE = 5
        const val GENRE_COVER_PATH = "genre"
        private const val GENRE_COVER_CODE = 6

        const val COOKIE_COVER_PATH = "cookie"
        private const val COOKIE_COVER_CODE = 7

        private val uriMatcher = UriMatcher(UriMatcher.NO_MATCH)
            .apply {
                addURI(AUTHORITY, "$SONG_COVER_PATH/*", SONG_COVER_CODE)
                addURI(AUTHORITY, "$ALBUM_COVER_PATH/*", ALBUM_COVER_CODE)
                addURI(AUTHORITY, "$ARTIST_COVER_PATH/*", ARTIST_COVER_CODE)
                addURI(AUTHORITY, "$ALBUM_ARTIST_COVER_PATH/*", ALBUM_ARTIST_COVER_CODE)
                addURI(AUTHORITY, "$PLAYLIST_COVER_PATH/*", PLAYLIST_COVER_CODE)
                addURI(AUTHORITY, "$GENRE_COVER_PATH/*", GENRE_COVER_CODE)
                addURI(AUTHORITY, "$COOKIE_COVER_PATH/*", COOKIE_COVER_CODE)
            }

        fun getImageUri(path: String, id: Long) = getImageUri(path, id.toString())
        fun getImageUri(path: String, id: String): Uri? {
            val uri = Uri.Builder()
                .scheme(ContentResolver.SCHEME_CONTENT)
                .authority(AUTHORITY)
                .appendPath(path)
                .appendPath(id)
                .build()
            if (uriMatcher.match(uri) > 0) {
                return uri
            }
            return null
        }

        fun clearCache(context: Context) {
            val cacheDir = context.cacheDir?.resolve(CACHE_DIR_NAME)
            if (cacheDir == null || !cacheDir.isDirectory) return

            val cacheFiles = cacheDir.listFiles()
            if (!cacheFiles.isNullOrEmpty()) for (file in cacheFiles) {
                if (!file.delete()) {
                    Log.d(TAG, "Failed to delete cache file $file")
                }
            }
        }
    }
}

private val Bitmap.CompressFormat.extension
    get() = if (this == Bitmap.CompressFormat.PNG) "png" else "jpg"

/** Built per call */
private fun Context.themedForFallback(): Context {
    // Night-qualified colors follow the configuration
    val night = when (Preferences.getDayNightMode()) {
        AppCompatDelegate.MODE_NIGHT_YES -> Configuration.UI_MODE_NIGHT_YES
        AppCompatDelegate.MODE_NIGHT_NO -> Configuration.UI_MODE_NIGHT_NO
        else -> resources.configuration.uiMode and Configuration.UI_MODE_NIGHT_MASK
    }
    val configuration = Configuration(resources.configuration).apply {
        uiMode = (uiMode and Configuration.UI_MODE_NIGHT_MASK.inv()) or night
    }

    val appTheme = createAppTheme()
    val themed = createConfigurationContext(configuration).apply { setTheme(appTheme.themeRes) }
    if (!appTheme.applyDynamicColors) return themed

    val options = DynamicColorsOptions.Builder()
        .apply { appTheme.seedColor?.let { setContentBasedSource(it) } }
        .build()
    val dynamic = DynamicColors.wrapContextIfAvailable(themed, options)
    return appTheme.dynamicColorOverlay?.let { ContextThemeWrapper(dynamic, it) } ?: dynamic
}

/** stable identity of already themed context */
private fun Context.placeholderKey(): String {
    val background = resolveColor(PlaceholderDrawable.BACKGROUND_COLOR, Color.DKGRAY)
    val foreground = resolveColor(PlaceholderDrawable.FOREGROUND_COLOR, Color.WHITE)
    return "%08x%08x".format(background, foreground)
}
