# GitHub Links
AUTHOR_GITHUB_URL=https://www.github.com/mardous
GITHUB_URL=https://www.github.com/mardous/BoomingMusic
RELEASES_LINK=https://www.github.com/mardous/BoomingMusic/releases
ISSUE_TRACKER_LINK=https://www.github.com/mardous/BoomingMusic/issues
COMMUNITY_LINK=https://www.github.com/mardous/BoomingMusic/wiki/Community
FAQ_LINK=https://www.github.com/mardous/BoomingMusic/wiki/FAQ

# External Links
DOWNLOAD_URL=https://www.github.com/mardous/BoomingMusic/releases/latest
TELEGRAM_COMMUNITY_LINK=https://t.me/mardousdev
DONATION_LINK=https://ko-fi.com/christiaam
TRANSLATIONS_LINK=https://hosted.weblate.org/engage/booming-music/

# API URLs
GITHUB_API_URL=https://api.github.com/
LASTFM_API_URL=https://ws.audioscrobbler.com/2.0/
LISTENBRAINZ_API_URL=https://api.listenbrainz.org/1/
LRCLIB_API_URL=https://lrclib.net/api/search
BETTERLYRICS_API_URL=https://lyrics-api.boidu.dev/getLyrics
LYRICALLY_API_URL=https://lyrics.paxsenix.org

# Web Search URLs
GOOGLE_SEARCH_URL=https://www.google.com/search?q=
LASTFM_MUSIC_URL=https://www.last.fm/music/
LASTFM_LOCALIZED_MUSIC_URL=https://www.last.fm/%s/music/
WIKIPEDIA_SEARCH_URL=https://www.wikipedia.org/wiki/Special:Search?search=
WIKIPEDIA_LOCALIZED_SEARCH_URL=https://%s.wikipedia.org/wiki/Special:Search?search=
YOUTUBE_SEARCH_URL=https://www.youtube.com/results?search_query=

# Support Email
SUPPORT_EMAIL=mardous.contact@gmail.com